---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "-car-app"
    labels: 
      app: "-car-app"
  spec: 
    selector: 
      matchLabels: 
        app: "-car-app"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "-car-app"
      spec: 
        containers: 
          - 
            name: "-car-app"
            image: "-car-app"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "-car-app"
    labels: 
      app: "-car-app"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "-car-app"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "car"
    labels: 
      app: "car"
  spec: 
    selector: 
      matchLabels: 
        app: "car"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "car"
      spec: 
        containers: 
          - 
            name: "car"
            image: "car"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "car"
    labels: 
      app: "car"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "car"
